#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
source "${SCRIPT_DIR}/env.sh"

log() {
  printf '[firesim-run] %s\n' "$*"
}

warn() {
  printf '[firesim-run][warn] %s\n' "$*" >&2
}

die() {
  printf '[firesim-run][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run-firesim-workloads.sh [options]

Default:
  Run every FireSim workload generated by scripts/package-firemarshal-workload.sh,
  then collect the latest model.log, autotune.log, and output.bin under
  scripts/figures/results-workload/<workload>/. For LLM workloads with sequence
  length greater than 256, output.bin is not collected because those workloads
  run with --no-output.

Options:
  --workload=NAME      Run/collect one workload. May be repeated or comma-separated.
  --collect-only       Do not invoke FireSim; collect the latest existing results.
  -h, --help           Show this help.

Environment:
  PYTORCH_CHIPYARD_FPGA_DB                  Default: /opt/firesim-db.json
  FIRESIM_RUNS_DIR                          Default: $WORKSPACE/FIRESIM_RUNS_DIR
  PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR      Generated config_runtime files.
  PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR     FireSim results-workload directory.
  PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR
                                             Collected result directory.
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST    Default: localhost
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC    Default: one_fpgas_spec
  PYTORCH_CHIPYARD_KEEP_RUNFARM=1           Skip terminaterunfarm.
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES
                                             Comma-separated workload=hw_config list.

Per-workload hardware override:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_<WORKLOAD>

Example:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_RESNET50_GEMMINI_4CORE=alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic \
    bash scripts/run-firesim-workloads.sh --workload=resnet50-gemmini-4core
EOF
}

validate_name() {
  local label="$1"
  local value="$2"
  [[ "${value}" =~ ^[A-Za-z0-9._-]+$ ]] || \
    die "invalid ${label} '${value}'; use only letters, numbers, '.', '_', and '-'"
}

require_file() {
  local path="$1"
  [[ -f "${path}" ]] || die "missing required file: ${path}"
}

require_dir() {
  local path="$1"
  [[ -d "${path}" ]] || die "missing required directory: ${path}"
}

yaml_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

split_workload_arg() {
  local value="$1"
  local item
  local -a items

  IFS=, read -r -a items <<<"${value}"
  for item in "${items[@]}"; do
    [[ -n "${item}" ]] || continue
    validate_name "workload" "${item}"
    SELECTED_WORKLOADS+=("${item}")
  done
}

discover_workloads() {
  local json path base workload

  [[ -d "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" ]] || return 0
  while IFS= read -r path; do
    base="$(basename "${path}")"
    workload="${base%.json}"
    case "${workload}" in
      br-base | *base)
        continue
        ;;
    esac
    validate_name "workload" "${workload}"
    printf '%s\n' "${workload}"
  done < <(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" -maxdepth 1 -type f -name '*.json' -print | sort -V)
}

unique_workloads() {
  local -A seen=()
  local workload

  for workload in "$@"; do
    [[ -n "${seen[${workload}]:-}" ]] && continue
    seen["${workload}"]=1
    printf '%s\n' "${workload}"
  done
}

load_workloads() {
  local workloads=()
  local workload

  if [[ "${#SELECTED_WORKLOADS[@]}" -gt 0 ]]; then
    mapfile -t workloads < <(unique_workloads "${SELECTED_WORKLOADS[@]}")
  else
    mapfile -t workloads < <(discover_workloads)
  fi

  [[ "${#workloads[@]}" -gt 0 ]] || \
    die "no packaged workloads found under ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"

  for workload in "${workloads[@]}"; do
    require_file "${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
    require_file "${FIRESIM_WORKLOAD_DIR}/${workload}.json"
  done

  WORKLOADS=("${workloads[@]}")
}

core_for_workload() {
  local workload="$1"

  if [[ "${workload}" =~ (^|-)([0-9]+)core($|-) ]]; then
    printf '%s\n' "${BASH_REMATCH[2]}"
    return 0
  fi

  return 1
}

is_llm_workload() {
  local workload="$1"

  case "${workload}" in
    gpt2-* | gpt-neo-* | opt-* | pythia-* | *tok*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

llm_seq_len_for_workload() {
  local workload="$1"

  if [[ "${workload}" =~ (^|-)([0-9]+)tok($|-) ]]; then
    printf '%s\n' "${BASH_REMATCH[2]}"
  else
    printf '%s\n' 256
  fi
}

should_collect_output_bin() {
  local workload="$1"
  local seq_len

  if is_llm_workload "${workload}"; then
    seq_len="$(llm_seq_len_for_workload "${workload}")"
    [[ "${seq_len}" -le 256 ]]
    return
  fi

  return 0
}

contains_tag() {
  local workload="$1"
  local tag="$2"

  case "-${workload}-" in
    *-"${tag}"-*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

env_suffix_for_workload() {
  local workload="$1"
  local suffix

  suffix="${workload^^}"
  suffix="${suffix//[^A-Z0-9_]/_}"
  printf '%s\n' "${suffix}"
}

override_hw_config_for() {
  local workload="$1"
  local suffix var_name overrides pair key value

  suffix="$(env_suffix_for_workload "${workload}")"
  var_name="PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_${suffix}"
  if [[ -n "${!var_name:-}" ]]; then
    printf '%s\n' "${!var_name}"
    return 0
  fi

  overrides="${PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES:-}"
  [[ -n "${overrides}" ]] || return 1

  IFS=, read -r -a pairs <<<"${overrides}"
  for pair in "${pairs[@]}"; do
    key="${pair%%=*}"
    value="${pair#*=}"
    [[ "${key}" == "${workload}" && "${value}" != "${pair}" && -n "${value}" ]] || continue
    printf '%s\n' "${value}"
    return 0
  done

  return 1
}

infer_hw_config() {
  local workload="$1"
  local core

  if override_hw_config_for "${workload}"; then
    return 0
  fi

  core="$(core_for_workload "${workload}")" || \
    die "could not infer core count from workload '${workload}'"

  if contains_tag "${workload}" "boom"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic" ;;
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_4core_no_nic" ;;
      *) die "no BOOM hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "gemmini"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic" ;;
      *) die "no Gemmini hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rvv"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic" ;;
      2) printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_2core_no_nic" ;;
      4)
        if is_llm_workload "${workload}"; then
          printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic"
        else
          printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic_30mhz"
        fi
        ;;
      *) die "no RVV hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rocket"; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  elif is_llm_workload "${workload}"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic" ;;
      *) die "no LLM fallback hardware config mapping for ${workload}" ;;
    esac
  elif [[ "${core}" == "16" ]]; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  else
    die "could not infer hardware config for workload '${workload}'; set PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_$(env_suffix_for_workload "${workload}")"
  fi
}

require_hw_config() {
  local hw_config="$1"

  require_file "${FIRESIM_HWDB_PATH}"
  require_file "${FIRESIM_BUILD_RECIPES_PATH}"

  if ! grep -q "^${hw_config}:" "${FIRESIM_HWDB_PATH}"; then
    die "hardware config '${hw_config}' not found in ${FIRESIM_HWDB_PATH}"
  fi
}

generate_runtime_config() {
  local workload="$1"
  local hw_config="$2"
  local runtime="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/config_runtime_${workload}.yaml"

  mkdir -p "${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}" "${FIRESIM_RUNS_DIR}"

  cat >"${runtime}" <<EOF
# Auto-generated by scripts/run-firesim-workloads.sh

run_farm:
  base_recipe: run-farm-recipes/externally_provisioned.yaml
  recipe_arg_overrides:
    default_platform: XilinxAlveoU250InstanceDeployManager
    default_simulation_dir: $(yaml_quote "${FIRESIM_RUNS_DIR}")
    default_fpga_db: $(yaml_quote "${PYTORCH_CHIPYARD_FPGA_DB}")
    run_farm_hosts_to_use:
        - $(yaml_quote "${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST}"): ${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC}

metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: verilator
  metasimulation_only_plusargs: "+fesvr-step-size=128 +max-cycles=100000000"
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"

target_config:
    topology: no_net_config
    no_net_num_nodes: 1
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: ${hw_config}
    plusarg_passthrough: ""

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: ${workload}.json
    terminate_on_completion: yes
    suffix_tag: ${workload}

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
EOF

  printf '%s\n' "${runtime}"
}

latest_result_dir() {
  local workload="$1"
  local marker="${2:-}"
  local newer_args=()

  [[ -d "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" ]] || return 1
  if [[ -n "${marker}" ]]; then
    newer_args=(-newer "${marker}")
  fi

  find "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" \
    -maxdepth 2 \
    -type d \
    -name "${workload}0" \
    "${newer_args[@]}" \
    -printf '%T@ %p\n' 2>/dev/null | \
    sort -nr | \
    head -n 1 | \
    cut -d' ' -f2-
}

copy_if_present() {
  local src="$1"
  local dst="$2"

  if [[ -f "${src}" ]]; then
    cp -f "${src}" "${dst}"
    return 0
  fi

  return 1
}

collect_workload_result() {
  local workload="$1"
  local marker="${2:-}"
  local result_dir dest copied=0

  result_dir="$(latest_result_dir "${workload}" "${marker}")"
  if [[ -z "${result_dir}" ]]; then
    warn "${workload}: no result directory found under ${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}"
    return 1
  fi

  dest="${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}/${workload}"
  mkdir -p "${dest}"

  if copy_if_present "${result_dir}/model.log" "${dest}/model.log"; then
    copied=1
  else
    warn "${workload}: missing model.log in ${result_dir}"
  fi

  if copy_if_present "${result_dir}/autotune.log" "${dest}/autotune.log"; then
    copied=1
  else
    warn "${workload}: missing autotune.log in ${result_dir}"
  fi

  if should_collect_output_bin "${workload}"; then
    if copy_if_present "${result_dir}/output.bin" "${dest}/output.bin"; then
      copied=1
    else
      warn "${workload}: missing output.bin in ${result_dir}"
    fi
  else
    rm -f "${dest}/output.bin"
    log "${workload}: skipped output.bin collection for seq > 256 LLM workload"
  fi

  [[ "${copied}" -eq 1 ]] || return 1

  log "${workload}: collected results from ${result_dir} -> ${dest}"
}

run_workload() {
  local workload="$1"
  local hw_config="$2"
  local runtime="$3"
  local marker="$4"
  local status=0
  local keep_runfarm="${PYTORCH_CHIPYARD_KEEP_RUNFARM:-${KEEP_RUNFARM:-0}}"

  log "${workload}: launchrunfarm/infrasetup/runworkload with ${hw_config}"

  (
    set -euo pipefail
    cd "${FIRESIM_DIR}"
    set +u
    source ./sourceme-manager.sh --skip-ssh-setup
    set -u

    firesim launchrunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?

    if [[ "${status}" -eq 0 ]]; then
      firesim infrasetup -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?
    fi

    if [[ "${status}" -eq 0 ]]; then
      firesim runworkload -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?
    fi

    if [[ "${keep_runfarm}" != "1" ]]; then
      firesim terminaterunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" --forceterminate || true
    fi

    exit "${status}"
  ) || status=$?

  collect_workload_result "${workload}" "${marker}" || true
  return "${status}"
}

COLLECT_ONLY=0
SELECTED_WORKLOADS=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --workload)
      [[ "$#" -ge 2 ]] || die "--workload requires a value"
      split_workload_arg "$2"
      shift 2
      ;;
    --workload=*)
      split_workload_arg "${1#--workload=}"
      shift
      ;;
    --collect-only)
      COLLECT_ONLY=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument '$1'; pass --help for usage"
      ;;
  esac
done

require_dir "${FIRESIM_DIR}"
require_dir "${FIRESIM_WORKLOAD_DIR}"

WORKLOADS=()
load_workloads

if [[ "${COLLECT_ONLY}" -eq 1 ]]; then
  mkdir -p "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}"
  for workload in "${WORKLOADS[@]}"; do
    collect_workload_result "${workload}" || true
  done
  exit 0
fi

require_file "${FIRESIM_DIR}/sourceme-manager.sh"
require_file "${PYTORCH_CHIPYARD_FPGA_DB}"

for workload in "${WORKLOADS[@]}"; do
  hw_config="$(infer_hw_config "${workload}")"
  require_hw_config "${hw_config}"
  runtime="$(generate_runtime_config "${workload}" "${hw_config}")"
  marker="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/.${workload}.run-start"
  mkdir -p "$(dirname "${marker}")"
  : >"${marker}"
  run_workload "${workload}" "${hw_config}" "${runtime}" "${marker}"
done
